 export const searchData = [
  {
    id: 1,
    type: "doctor",
    name: "Dr. John Doe",
    specialty: "Cardiologist",
    location: "City Hospital",
    hospital: "Medanta",
  },
  {
    id: 2,
    type: "doctor",
    name: "Dr. Sarah Smith",
    specialty: "Dermatologist",
    location: "Sunrise Clinic",
    hospital: "Apollo Hospitals",
  },
  {
    id: 3,
    type: "doctor",
    name: "Dr. Robert Johnson",
    specialty: "Orthopedic Surgeon",
    location: "Metro Medical Center",
    hospital: "Fortis Hospital",
  },
  {
    id: 4,
    type: "hospital",
    name: "Sunset General Hospital",
    location: "Downtown",
    services: ["Emergency Care", "Surgery", "Radiology"],
  },
  {
    id: 5,
    type: "hospital",
    name: "Unity Medical Center",
    location: "Suburbia",
    services: ["Maternity", "Pediatrics", "Cardiology"],
  },
  {
    id: 6,
    type: "hospital",
    name: "Greenview Health Campus",
    location: "Rural Area",
    services: ["Internal Medicine", "Physical Therapy"],
  },
  {
    id: 7,
    type: "doctor",
    name: "Dr. Sarah Smith",
    specialty: "Dermatologist",
    location: "Sunrise Clinic",
    hospital: "Apollo Hospitals",
  },
  {
    id: 8,
    type: "doctor",
    name: "Dr. Robert Johnson",
    specialty: "Orthopedic Surgeon",
    location: "Metro Medical Center",
    hospital: "Fortis Hospital",
  },
  {
    id: 9,
    type: "doctor",
    name: "Dr. Priya Sharma",
    specialty: "Pediatrician",
    location: "Sunrise Clinic",
    hospital: "Apollo Hospitals",
  },
  {
    id: 10,
    type: "doctor",
    name: "Dr. Anjali Desai",
    specialty: "Ophthalmologist",
    location: "Metro Medical Center",
    hospital: "Fortis Hospital",
  },
  {
    id: 11,
    type: "doctor",
    name: "Dr. Arjun Singh",
    specialty: "Neurologist",
    location: "Greenview Hospital",
    hospital: "Greenview Health Campus",
  },
  {
    id: 12,
    type: "doctor",
    name: "Dr. Naina Patel",
    specialty: "ENT Specialist",
    location: "Unity Medical Center",
    hospital: "Unity Medical Center",
  },
  {
    id: 13,
    type: "doctor",
    name: "Dr. Alok Verma",
    specialty: "Cardiologist",
    location: "City Hospital",
    hospital: "Medanta",
  },
  {
    id: 14,
    type: "doctor",
    name: "Dr. Ananya Kapoor",
    specialty: "Dermatologist",
    location: "Sunrise Clinic",
    hospital: "Apollo Hospitals",
  },
  {
    id: 15,
    type: "doctor",
    name: "Dr. Rajesh Kumar",
    specialty: "Orthopedic Surgeon",
    location: "Metro Medical Center",
    hospital: "Fortis Hospital",
  },
  {
    id: 16,
    type: "doctor",
    name: "Dr. Sneha Sharma",
    specialty: "Pediatrician",
    location: "Sunrise Clinic",
    hospital: "Apollo Hospitals",
  },
  {
    id: 17,
    type: "doctor",
    name: "Dr. Nisha Gupta",
    specialty: "Gastroenterologist",
    location: "City Hospital",
    hospital: "Medanta",
  },
  {
    id: 18,
    type: "doctor",
    name: "Dr. Anand Deshmukh",
    specialty: "Ophthalmologist",
    location: "Metro Medical Center",
    hospital: "Fortis Hospital",
  },
  {
    id: 19,
    type: "doctor",
    name: "Dr. Neha Singh",
    specialty: "Neurologist",
    location: "Greenview Hospital",
    hospital: "Greenview Health Campus",
  },
  {
    id: 20,
    type: "doctor",
    name: "Dr. Vivek Patel",
    specialty: "ENT Specialist",
    location: "Unity Medical Center",
    hospital: "Unity Medical Center",
  },
  {
    id: 21,
    type: "doctor",
    name: "Dr. Rajesh Kapoor",
    specialty: "Gastroenterologist",
    location: "City Hospital",
    hospital: "Medanta",
  },
];
