const specialtiesData = [
    { id: 1, name: 'Cardiology' },
    { id: 2, name: 'Dermatology' },
    { id: 3, name: 'Orthopedics' },
    { id: 4, name: 'Neurology' },
    { id: 5, name: 'Ophthalmology' },
    { id: 6, name: 'Gastroenterology' },
    { id: 7, name: 'Endocrinology' },
    { id: 8, name: 'Pediatrics' },
    { id: 9, name: 'Oncology' },
    { id: 10, name: 'Psychiatry' },
    { id: 11, name: 'Gynecology' },
    { id: 12, name: 'Urology' },
    { id: 13, name: 'Pulmonology' },
    { id: 14, name: 'Rheumatology' },
    { id: 15, name: 'Nephrology' },
    { id: 16, name: 'Hematology' },
    { id: 17, name: 'Infectious Disease' },
    { id: 18, name: 'Allergy' },
    { id: 19, name: 'Radiology' },
    { id: 20, name: 'Medicine' },
    { id: 21, name: 'Rehabilitation' },
    { id: 22, name: 'Anesthesiology' },
    { id: 23, name: 'Dentistry' },
    { id: 24, name: '(ENT)' },
    { id: 25, name: 'Geriatrics' },
  ];
  
  export default specialtiesData;
  